### ISSUE TITLE
Add certificate verification events

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#116]
In real deployments, getting some feedback on certificate validation events is useful (e.g., these are included in NetLog).

I wonder if these can be done as triggers... but on what event would those triggers be logged then? Maybe on a connection close if validation fails? What if it succeeds? 

As I've seen some discussion about these things being async and sometimes depend on remote fetches (e.g., for OCSP), it would probably be useful to have separate events though. 

I need to get a better overview of the types of events though to decide on how to log this. Probably add something simple for draft-02 and extend in -03.

**Comment by LPardue** [comment]
This falls into the camp of something the application does, rather than a transport feature. 

When a handshake fails, there are protocol messages that communicate that. We support them already AFAIK.

Extra information is useful for debugging but qlog is flexible enough to let application do what ever they want. 

Suggest close with no action; reopen if there is clear demand for a specific event.

**Comment by marten-seemann** [comment]
This also seems to fall into the realm of a TLS qlog extension.

**Comment by rmarx** [comment]
Agreed to close with no action, as this leans more towards top-level Application or low-level TLS, neither of which we do (much of) today.
