### ISSUE TITLE
the new Token is confusing

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/qlog#122]
The `Token` introduced in https://github.com/quiclog/internet-drafts/commit/60690f4033624006b5bbac8797e69b8a78331ce3 doesn't make sense to me. I don't see the motivation for bundling stateless resets and Retry tokens into the same struct (other than incidentally, the spec calls them tokens).

Stateless reset tokens are by definition random values (or rather, a deterministic pseudorandom value derived from the connection ID). They are always 16 bytes and never contain any other information.

On the other hand, the token sent on the Initial can be a Retry token or a NEW_TOKEN token (I guess that's what a resumption token is). This token typically does contain additional information encoded into the value (in fact, as I've described in https://github.com/quiclog/internet-drafts/issues/117#issuecomment-692603028, the spec mandates that you encode a bunch of values into that token). I would have wished that at least those mandatory fields are clearly defined in the `Token`.

**Comment by rmarx** [comment]
From a discussion on Slack, @marten-seemann is in favor of splitting stateless reset tokens from the Token class and logging them as a `stateless_reset_token?:bytes` (which is the approach we had before and works well because the reset token is always 128 bits in length).

Wrt to specifying detail fields, from what I can gather there are two main ones:
- `remote_address?:IPAddress` for a NEW_TOKEN 
- `timeout?:uint32` for a retry token

Are there others that would benefit from being specified explicitly?

**Comment by marten-seemann** [comment]
I think most implementations encode the timestamp (and not the timeout) when the token was generated into the token, so they can decide if they want to accept a token based on current conditions.
