### ISSUE TITLE
Format text to a certain width and avoid inline comments

### ISSUE THREAD

**Issue by toidiu** [quicwg/qlog#148]
Inline comments force the reader to scroll sideways and makes it more difficult to read.

Additionally while this is possibly fine for html, the rendering in pdf is much worse since scrolling is not supported.

**html example**: https://quiclog.github.io/internet-drafts/draft-marx-qlog-event-definitions-quic-h3.html#section-a.1

 **pdf example**:
![pdf_rendering](https://user-images.githubusercontent.com/4350690/113912463-00d55d80-9790-11eb-9c05-e5abfea0b81e.png)

**Comment by rmarx** [comment]
Hello @toidiu,

Thank you for this very valid comment. 
We will take this into account when re-formatting the qlog documents after adoption by the QUIC wg. 

I hope it doesn't cause too much of an inconvenience in the mean time?

**Comment by toidiu** [comment]
Great thanks for the reply and all your work. I can use the html version of the draft in the meanwhile.

**Comment by rmarx** [comment]
Should be fixed in main-schema-02 and h3/quic-events-01 now. 

We've taken pains to prevent too-long inline comments in code blocks (max 72 characters per line) and to put comments above instead of behind fields. 

Feel free to take a look at the new drafts (e.g., https://www.ietf.org/archive/id/draft-ietf-quic-qlog-h3-events-01.html and https://www.ietf.org/archive/id/draft-ietf-quic-qlog-quic-events-01.html) and let us know if this is still not ideal @toidiu. 

Closing this issue for now, but feel free to re-open/comment if you find further problems.
