### ISSUE TITLE
PCAPML and metadata integration in general

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#157]
I recently came across this interesting project that tags traffic in pcaps for Machine Learning purposes: https://github.com/nprint/pcapml

This general concept of keeping traffic traces and metadata describing that data in the same file is one of the things I had envisioned for qlog at the start as well (i.e., combining traces into a single file, the `configuration` field, the ability to add new fields to events at will, etc.). This goal has diminished somewhat over time, but I'm still a big proponent of it.

I feel we should take a look at PCAPML to see how they're approaching this and decide if similar setups should be *possible* in qlog (though probably not part of the core spec).

**Comment by LPardue** [comment]
hmmm. Anything is possible, right? It's interesting for sure but seems outside our tight scope of work. I'm not seeing much traction on the issue since it got opened. Suggest closing and reopening if someone comes back with a strong use case we can't accomodate, or information about a current implementation of this technique applied to qlog.

**Comment by rmarx** [comment]
Agree to close without action.
