### ISSUE TITLE
Discuss how to approach extensions short term

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#170]
With several extensions to QUIC and HTTP/3 being developed, we should have some way of defining qlog events for them.

Given that most of these extensions are not RFC's in their own right, it doesn't make much sense to add them to the main documents at this time (or ever). 

Concrete examples:
- WebTransport having new stream types that impact the existing H3 `stream_type_set` event
- DATAGRAM and CAPSULE frames that should be defined
- CONNECT-UDP related metadata etc. 

Proposal:
- Specify qlog events for these in separate documents **in a separate repository** (potentially a new aggregate one at https://github.com/quiclog? Assuming people won't want to make separate docs themselves).

Long term, we need a proper way to do this, but for now I think something like this might suffice.

cc @LPardue

**Comment by LPardue** [comment]
So I don't think we need to concern the current QUIC WG qlog docs with work being done outside the group.

I do think we should probably accommodate QUIC DATAGRAMS in the qlog schema (because that draft will be done before qlog). 

H3 DATAGRAMS and Capsules should be out of scope here. We could entertain the idea of defining them as part of the h3 datagram spec itself, but with the open questions about schema format etc that's probably not really feasible.

**Comment by rmarx** [comment]
Related to #124
