### ISSUE TITLE
Decide if streaming serialization needs to be defined

### ISSUE THREAD

**Issue by LPardue** [quicwg/qlog#172]
The document includes considerations about streaming serialization and specifies a way to do this using NDJSON (new-line delimited JSON).

There's two things that the Working Group should consider:

1) Does streaming serialization need to be defined as part of the qlog main schema?
2) If the answer to 1 is yes, what format should be used.

During IETF 111, it was noted that https://datatracker.ietf.org/doc/html/rfc7464 is an IETF-defined format that achieves similar streaming properties as NDJSON.  There might be a preference for using RFC 7464 pending the outcome of #144.

**Comment by rmarx** [comment]
As discussed previously, I have now experimented with the "JSON text sequences" format described in https://datatracker.ietf.org/doc/html/rfc7464. 

While it is a bit annoying to have to add the RecordSeparator (RS, %x1E, U+001E) character before each event, in practice it was easy enough to integrate the new format with tools like [qvis ](https://github.com/quiclog/qvis/commit/9eaf25b67fa7a5128874f1e0dc3f1f623908439a)and use it with existing tools like jq, grep, sed and awk. 

As such, we propose to indeed replace the NDJSON format in draft-00 with the RFC 7464 format. This has several advantages, among which: 
1. having an existing RFC to refer to instead of having to define the format in qlog itself (since NDJSON is not an official standard anywhere)
2. having an existing mime-type `application/json-seq`  (see also #158)
3. supporting "pretty printed" JSON (records/events can span multiple lines), while NDJSON does not support \n characters in an event

I will create a PR to make this change in the text. Below are some example files and practical guidelines for those who wish to start experimenting with this themselves. cc @marten-seemann 

------------

[This zip file](https://github.com/quicwg/qlog/files/7374539/json-seq.zip) contains 2 files in both NDJSON, line-based json-seq and pretty-printed json-seq formats. 

These were generated by taking quic-go NDJSON outputs from https://interop.seemann.io and then adding the RecordSeparator character to them using the following sed monstrosity: 

```
# adapted from https://blog.jpalardy.com/posts/handling-broken-json-with-jq/#an-example

cat ndjsoninput1.qlog | sed -e 's/^{/'$(printf "\x1e")'{/' -e '$a\\n' | jq -c --seq . > textseqoutput1.qlog

# NOTE: if the last record isn't properly closed with a LineFeed \n, then jq will SILENTLY drop the final event in the file...
# this is why we add the  -e '$a\\n'  command, which selects the final line with $, enters append mode with a, and then adds \n
# if we have too many \n's, they are discarded, so this is safe

# jq -c is used to pretty-print the output. If that's not needed, the jq command can be left out. 
```

I then also changed the "qlog-format" field on the first line to "JSON-SEQ" (instead of "NDJSON"). That should be enough to get the files to load in qvis ("qlog-version" is currently still "draft-02", we'll probably want to change that for the upcoming ietf-draft-01).

Of course, implementations that output the new format should just output the \x1E character directly instead of post-processing the files like this... how to do that depends on the programming language of course.


I then also tested the json-seq files with some common tooling, especially `jq`. `jq` has built-in support for text-sequences by passing in the option `--seq`. With the option on, `jq` should also still be able to process normal JSON and NDJSON, so it should be safe to "leave it on", no matter which qlog format you're processing.

For example:
```
cat textseqoutput1.qlog | jq --seq -c '. | select(.data.header?.packet_type? == "handshake")'
``` 

Feel free to test this out yourselves and let me know if you find problems with the new format!

**Comment by rmarx** [comment]
We haven't heard major pushback against this since the introduction, so I'm going to close this issue for now.
