### ISSUE TITLE
Should custom CDDL types be defned externally?

### ISSUE THREAD

**Issue by LPardue** [quicwg/qlog#196]
In https://www.ietf.org/archive/id/draft-ietf-quic-qlog-main-schema-02.html#section-1.1.1 you define `uint8`, `uint16`, `uint32`, `uint64` and `hexstring`types.

Have you considered if these types should be defined in their own document? This seems like something where direction from the CBOR WG would be good.

**Comment by rmarx** [comment]
I agree guidance from the CBOR WG would be good, but I do feel they can just remain in the main qlog document, since there are so few and they are very straightforward.

I still have to explore some examples Carsten Bormann sent me of other RFCs using CDDL; maybe I can find some prior work that shows best practices in this.

**Comment by LPardue** [comment]
Yes agreed. Let's try and lock this down so we don't have to revisit it later when it might be more awkward and become a blocker to finishing.

**Comment by LPardue** [comment]
I don't want to do this, so I'm closing the issue.
