### ISSUE TITLE
Putting event data definitions in the appendix doesn't feel right

### ISSUE THREAD

**Issue by LPardue** [quicwg/qlog#221]
This also relates to https://github.com/quicwg/qlog/issues/220

In both the QUIC and H3 documents, the interesting data of each event is defined in the appendix. Typically, appendicesare used for only additional or informative content. 

Since the data is part of the normative schema, I'd suggest the definitions need to be promoted into the main body of the text.

**Comment by rmarx** [comment]
Agreed this shouldn't be in appendix.

Do want to keep the data definitions together though, instead of e.g., defining each where they are first used in an event. 

Since you are splitting the event categories into a Section per Category @LPardue, would this mean 1 new top-level Section for the data definitions (so just lift them up from appendices as they are) or split out more?
