### ISSUE TITLE
revisit old / new fields in various events

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/qlog#242]
One might argue that having an `old` field doesn’t make any sense, since you can just have a look at the last event to see what the value was.

We should consider removing the `old` field (and maybe renaming the `new` field).

**Comment by rmarx** [comment]
For context: I chose the old/new approach for `*Updated` events because:

1. You often start with a "default" value (e.g., for MTU) that you update later, but you wouldn't log the initial value (as that's part of the standard config), or at least not as an `Updated` event (though you -should- in that case)
2. When streaming logs in e.g., a "ring buffer" style, you might loose earlier events, making it impossible to track full history. Having both old and new in 1 event would help with this. This is a use case sometimes mentioned by @nibanks 

One of the main things I dislike is the naming of the `new` field. It would be nicer to have a name matching the semantics better (e.g., `stream_state` instead of `new` in `stream_state_updated` event). 

At this time, I don't have a strong preference for keeping old/new or changing to another scheme.

**Comment by rmarx** [comment]
I assume my answer was satisfactory @marten-seemann? I'm still in favor of keeping the ability to log older values though, and lacking a better proposal, I'll close this for now.
