### ISSUE TITLE
Should congestion_state_updated define some values for old and new?

### ISSUE THREAD

**Issue by LPardue** [quicwg/qlog#246]
congestion_state_updated fields include an `old` and `new` field that takes a `text` type. The prose that explains this event includes examples "slow_start, congestion_avoidance, application_limited, recovery"

Perhaps we should make these actual values in CDDL, add the BBR CC phases, and support general text too.

**Comment by rmarx** [comment]
So, from this recent discussion https://github.com/quicwg/qlog/issues/377 it seems @LPardue might not hold the same opinion anymore as he did 2 years ago when asking for this? :) 

I agree with the newer view that it doesn't make too much sense to define congestion control names/parameter values/phases/etc. because they're often different between implementations.

Propose to close this issue without action.

**Comment by LPardue** [comment]
I can live with this. However, I think we should adjust the examples to talk about abstract events rather than use strings. The reason being that the values suggest something that is standard, when we explicitly aren't doing that. So in other words let's talk about Slow Start and Application limited but refrain from using stingified renderings of them

**Comment by rmarx** [comment]
Took a stab at this at https://github.com/quicwg/qlog/pull/408. PTAL @LPardue
