### ISSUE TITLE
Revisit use of datagram_id

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#281]
Currently, we have a mechanism for tracking QUIC packet coalescing in a single UDP datagram by means of the `datagram_id` field. This was originally added as per #91. 

Main intended use: when a UDP payload is received containing multiple coalesced QUIC packets, those QUIC packets are given the same "datagram ID" (which is a receiver-side chosen number that's unique per received datagram, which is needed because UDP datagrams don't have a packet number or similar). As such, when 2 separate packets are logged in 2 separate `packet_received` events, but they have the same value for the `datagram_id` field, it's clear they were coalesced. Similarly, 2 `packet_sent` events with the same `datagram_id` indicate sender-side coalescing. 

As the original issue #91 indicates, this can be deduced from the `datagram_*` events as well, but those are often too chatty to leave on. The `datagram_ids` fields on the `datagram_*` events are for completeness / ability to track coalesced packets across the different events. 

I'm personally not the biggest fan of this solution (did you eventually implement this in quic-go, @marten-seemann?), but I don't immediately see a better approach.

CC @LPardue as he indicated the use of `datagram_id` wasn't clear to him, which means we either need to revisit or clarify its use.

**Comment by LPardue** [comment]
I'll try to summarise my understanding. 

The `datagram_id` is specified for the following events

* packet_sent
* packet_received
* packet_buffered
* packet_dropped
* datagrams_sent (an array here, but same purpose)
* datagrams_received (an array here, but same purpose)

The use of the ID is given in https://quicwg.org/qlog/draft-ietf-quic-qlog-quic-events.html#name-datagrams_sent and currently says:

> Note: QUIC itself does not have a concept of a "datagram_id". This field is a purely qlog-specific construct to allow tracking how multiple QUIC packets are coalesced inside of a single UDP datagram, which is an important optimization during the QUIC handshake. For this, implementations assign a (per-endpoint) unique ID to each datagram and keep track of which packets were coalesced into the same datagram. As packet coalescing typically only happens during the handshake (as it requires at least one long header packet), this can be done without much overhead.

I don't mind the motivating use case. I'm not sure exactly how my implementations could use it for packet sending events because we generate the packet and qlog it before we get into UDP datagram realms. Changes might address that but I'm not sure it's worth overhead. Other implementations might find it far more natural to use though.

The main part I find confusing is the part about `implementations assign a per-endpoint unique ID`. This is vague and quite specific at the same time. How unique does something need to be? Can I just use a counter like datagram_id = 0, datagram_id=1 for the packets sent on a connection? Or is the expectation that the identifier is more like a UUID, so that  packets are uniquely traceable? Maybe it depends if we are capturing single connections or traces that span mutliple things, so perhaps a reword to state the requirements and expectations of the datagram_id value could help. E.g. "Since QUIC traces may contain many UDP events, unique identifiers are required for each datagram in order to avoid them being confused. Identifiers are not exchanged on the wire, they are only relevant to the logging endpoint. Selecting identifier values is left to implementations that should consider how to generate unique values within the scope of the traces they generate"
