### ISSUE TITLE
Think about usage in proxies

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#42]
If qlog is used on a proxy, the question becomes what vantage_point it should use for its traces, since it's now simultaneously accepting and opening connections, and thus behaves as both a client and a server.

One approach would be to have (two) separate traces with separate vantage_points, but if there is a 1-to-1 mapping between client -> proxy -> origin connections, it -might- make sense to log everything into one trace (though I would need to reflect more on this). 

In this latter case, it might make sense to add a "role" or "vantage_point" indication to events like `connection_started`.

Thanks to @hawkinsw for reporting.
Maybe @LPardue has some comments, given his experience with the proxy-ing use case?

**Comment by LPardue** [comment]
I'd lean on the side of do-nothing right now. Why? Because rfc 9000 doesn't even mention proxies.

We could try to build a design around how HTTP proxying works. In HTTP, proxies are both a server and a client. But trying to be overly helpful here in qlog risks snowballing due to various forms of proxy and how they are deployed. E.g., a common deployment strategy is to chain proxies with different connection characteristics that carry HTTP semantics. You can quickly turn what sounds like a simple 1:1 pipeline into a many:1 or 1:many. Typically this sort of thing can be dealt with via distributed tracing, which depends on a common identifier being propagated around and used to stich back together things. 

Proxing with QUIC using MASQUE approaches is prevalent. I'd personally like to do something better there. But primarily a proxy is converting a QUIC stream into a TCP or UDP transport, which are outside our focus right now. If your're tunneling QUIC via CONNECT, what actually tends to happen is that the client produces two `client` role logs, and the server produces just one `server` role log.

In closing, I'd want to hear real proxy operator pain points or solutions for qlog. Otherwise we'd be designing in a vacuum, or designing something that is not of any real use.

**Comment by marten-seemann** [comment]
I agree with @LPardue that this should live in a qlog extension. Maybe CONNECT-UDP would be a good candidate to define such an extension, once the qlog RFC is on its way.

**Comment by rmarx** [comment]
Agreed with both to close with no action for now.
I'd say since e.g., Cloudflare is using qlog in this proxied setting already, it's probably somewhat possible to employ it usefully today and can be extended to be more ergonomic later.
