### ISSUE TITLE
Extensions to events can not be indicated by schema

### ISSUE THREAD

**Issue by LPardue** [quicwg/qlog#432]
Here's a summary of what qlog already permits

* Define new event schema
  * Define new namespaces, if desired 
* Define new categories
  * In existing namespaces, if desired 
* Define new event types in new categories
  * Existing categories cannot be extended
* Extend any event that allows it with new fields

For example, the QUIC packet_sent event is extensible. Cloudflare has a custom field called send_at_time that we use (see https://github.com/quicwg/qlog/issues/297 for background). If I want to formally define that extension point with a schema, the current event_schemas mechanism doesn't quite work well. While I could define a new namespace, category ID and event type - that's a lot of overhead for adding just a single field to an existing event. This also makes it hard to compose extensions together.

Proposal: define a new type of schema that is scoped to cover only extensions to existing event types, which is indicated by a value in the URI e.g., where we have `urn:ietf:params:qlog:events:gen#loglevel` a standardized extension `foo` could be identified by `urn:ietf:params:qlog:event_ext:extension_foo`, a private extension could be identified by `https://example.com/032024/event_ext/extension_foo.html`

**Comment by rmarx** [comment]
After my long comment above and thinking about it some more + a long discussion with Lucas, we decided it would make most sense to just remove categories from qlog altogether.

I originally used categories because I thought events would be re-usable across protocols, but in practice, this was a pipe dream anyway. They just made extensibility and naming (and even implementations) more difficult while adding little to no value. 

#439 removes categories and consequently makes it possible to be more flexible in how we extend qlog, including with new documents that just extend existing events in existing namespaces, and it thus also closes this issue as solved.
